site_name: Sifu
site_url: https://sifu-ai.readthedocs.io/
site_author: Sifu Team
repo_url: https://github.com/yourusername/sifu
repo_name: yourusername/sifu

# Copyright
copyright: 'Copyright &copy; 2023 Sifu Team'

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.action.edit
    - content.action.view

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - toc:
      permalink: true
      separator: '-'

# Navigation
extra_navbar: |
  <a href="https://github.com/yourusername/sifu" target="_blank" rel="noopener">
    <span class="twemoji">
      {% include ".icons/fontawesome/brands/github.svg" %}
    </span>
    GitHub
  </a>

extra_css:
  - css/extra.css

# Plugins
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_full_path: false
            show_root_heading: true
            show_root_toc_entry: true
            show_signature: true
            show_signature_annotations: true

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting_started/installation.md
    - Quick Start: getting_started/quickstart.md
    - Configuration: getting_started/configuration.md
  - User Guide:
    - Core Concepts: user_guide/core_concepts.md
    - Knowledge Base: user_guide/knowledge_base.md
    - Context Management: user_guide/context.md
    - Intent Matching: user_guide/intent_matching.md
    - Learning: user_guide/learning.md
  - API Reference:
    - API Overview: api_reference/overview.md
    - Knowledge API: api_reference/knowledge_api.md
    - Context API: api_reference/context_api.md
    - Learning API: api_reference/learning_api.md
  - Development:
    - Setup: development/setup.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md
    - Deployment: development/deployment.md
    - Contributing: development/contributing.md
  - Examples:
    - Basic Usage: examples/basic_usage.md
    - Advanced Usage: examples/advanced_usage.md
  - About:
    - Changelog: about/changelog.md
    - License: about/license.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/sifu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sifu_ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/your-invite-link
